---
deployment:
  tasks:
    - export DEPLOYPATH=/home/agasitco/public_html/proyagasit   # Ruta donde se desplegarán los archivos
    - /bin/cp -R * $DEPLOYPATH  # Copia todos los archivos al directorio de despliegue
