deployment:
  tasks:
    - export DEPLOYPATH=/home/agasitco/public_html

    # Sincronizar archivos CSS
    - echo "Sincronizando archivos CSS..."
    - rsync -avz css/ $DEPLOYPATH/css/

    # Sincronizar archivos de im치genes
    - echo "Sincronizando archivos de im치genes..."
    - rsync -avz img/ $DEPLOYPATH/img/

    # Sincronizar archivo JavaScript principal
    - echo "Sincronizando archivo JavaScript principal..."
    - rsync -avz main.js $DEPLOYPATH/

    # Sincronizar bibliotecas
    - echo "Sincronizando bibliotecas..."
    - rsync -avz lib/ $DEPLOYPATH/lib/

    # Sincronizar archivos SCSS (si es necesario en el servidor)
    - echo "Sincronizando archivos SCSS..."
    - rsync -avz scss/ $DEPLOYPATH/scss/

    # Sincronizar archivos HTML
    - echo "Sincronizando archivos HTML..."
    - rsync -avz *.html $DEPLOYPATH/

    # Verificaci칩n de archivos sincronizados
    - echo "Verificaci칩n de archivos sincronizados"
    - ls -l $DEPLOYPATH
